node {

    checkout scm

    docker.withRegistry('https://registry.hub.docker.com', 'dockerHub') {

        def customImage = docker.build("mgafar/springboot")

        /* Push the container to the custom Registry */
        customImage.push()
    }
}